import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appShell: { flex: 1, padding: 24, backgroundColor: '#0f172a' },
  menuFab: {
    position: 'absolute',
    top: 24,
    right: 24,
    zIndex: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#1e40af',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#3b82f6',
  },
  menuButtonLabel: { color: '#fff', fontWeight: '700', fontSize: 14 },
  appLayout: { flex: 1, paddingTop: 80, paddingHorizontal: 12 },
  mainContent: { flex: 1, maxWidth: 1400, alignSelf: 'center', width: '100%' },
  sidebarOverlay: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    zIndex: 20,
  },
  sidebarBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.8)' },
  sidebarPanel: {
    width: 320,
    backgroundColor: '#1e293b',
    paddingVertical: 32,
    paddingHorizontal: 24,
    borderLeftWidth: 2,
    borderLeftColor: '#334155',
    borderRadius: 0,
  },
  sidebarItem: { paddingVertical: 14, paddingHorizontal: 20, borderRadius: 4, marginBottom: 6, borderWidth: 1, borderColor: 'transparent' },
  sidebarItemActive: { backgroundColor: '#1e40af', borderColor: '#3b82f6' },
  sidebarLabel: { color: '#cbd5e1', fontWeight: '600', fontSize: 15 },
  sidebarLabelActive: { color: '#fff' },
  sidebarDivider: { height: 1, backgroundColor: '#334155', marginTop: 14, marginBottom: 14 },
  sidebarExitItem: { borderColor: '#7f1d1d', backgroundColor: 'rgba(127, 29, 29, 0.2)' },
  sidebarExitLabel: { color: '#fecaca' },
  fab: {
    position: 'absolute',
    right: 32,
    bottom: 32,
    backgroundColor: '#1e40af',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#3b82f6',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 6,
  },
  fabLabel: { color: '#fff', fontWeight: '700', fontSize: 14 },
  featureContent: { paddingBottom: 60, paddingHorizontal: 24 },
  featureHeadline: { fontSize: 22, fontWeight: '800', color: '#f8fafc', marginBottom: 12 },
  featureSubtitle: { color: '#94a3b8', marginBottom: 20, fontSize: 16 },
  featureCard: {
    backgroundColor: '#1e293b',
    padding: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: 'rgba(0,0,0,0.2)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: 16,
  },
  promptCard: { marginBottom: 12 },
  promptLabel: { fontWeight: '700' },
  promptText: { color: '#e5e7eb', marginVertical: 6 },
  promptButton: { alignSelf: 'flex-start', padding: 8, backgroundColor: '#2563eb', borderRadius: 8 },
  promptButtonLabel: { color: '#fff', fontWeight: '700' },
  textArea: { backgroundColor: '#1e293b', borderRadius: 6, padding: 16, minHeight: 140, marginBottom: 16, borderWidth: 1, borderColor: '#334155', fontSize: 15, color: '#f8fafc' },
  toggleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, paddingVertical: 8 },
  toggleLabel: { fontWeight: '600', fontSize: 15, color: '#e2e8f0' },
  toggleHelper: { color: '#94a3b8', fontSize: 13 },
  primaryButton: { backgroundColor: '#1e40af', padding: 16, borderRadius: 6, alignItems: 'center', marginVertical: 16, borderWidth: 1, borderColor: '#3b82f6' },
  primaryButtonDisabled: { opacity: 0.5, backgroundColor: '#475569' },
  primaryLabel: { color: '#fff', fontWeight: '700', fontSize: 15 },
  errorBox: { backgroundColor: '#fee2e2', padding: 10, borderRadius: 8 },
  errorText: { color: '#991b1b' },
  resultCard: { marginVertical: 12 },
  resultScore: { fontSize: 36, fontWeight: '800' },
  resultSubtitle: { color: '#9ca3af', marginBottom: 8 },
  resultMetricsRow: { flexDirection: 'row', gap: 8, marginVertical: 8 },
  metricPill: { padding: 8, backgroundColor: '#111827', borderRadius: 8, alignItems: 'center', marginRight: 8 },
  metricValue: { fontWeight: '800' },
  metricLabel: { fontSize: 12, color: '#9ca3af' },
  sectionTitle: { fontWeight: '700', marginTop: 12 },
  emptyText: { color: '#9ca3af', marginTop: 6 },
  badgeRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6 },
  badgeLabel: { fontWeight: '700' },
  badgeMeta: { color: '#2563eb', fontWeight: '700' },
  penaltyCard: { backgroundColor: '#fff1f2', padding: 8, borderRadius: 10, marginTop: 6 },
  penaltyTitle: { fontWeight: '800', color: '#9f1239' },
  penaltyText: { color: '#9f1239' },
  historyCard: { marginTop: 12 },
  historyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  clearHistory: { color: '#9ca3af' },
  historyRow: { paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#eef2f7' },
  historyMeta: { flexDirection: 'row', gap: 8, marginBottom: 4 },
  historyLevel: { fontWeight: '700' },
  historyMode: { color: '#9ca3af' },
  historyScore: { marginLeft: 'auto', fontWeight: '700' },
  historyText: { color: '#e5e7eb' },
  historyTimestamp: { color: '#9aa0a6', fontSize: 12, marginTop: 4 },
  kanjiGrid: { display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  kanjiCell: { width: 80, height: 80, borderRadius: 4, backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#334155' },
  kanjiChar: { fontSize: 32, color: '#f8fafc' },
  kanjiCount: { color: '#94a3b8', marginTop: 12, fontSize: 14 },
  calendarLayout: { flex: 1, width: '100%', flexDirection: 'column', gap: 16 },
  calendarBoard: { marginBottom: 20 },
  calendarBoardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, paddingHorizontal: 4 },
  calendarHeaderButton: { padding: 12, borderRadius: 6, borderWidth: 1, borderColor: '#3b82f6', backgroundColor: '#1e40af' },
  calendarHeaderButtonLabel: { fontSize: 14, fontWeight: '700', color: '#ffffff' },
  calendarBoardTitle: { color: '#e5e7eb', fontSize: 18, fontWeight: '700' },
  calendarWeekdays: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  calendarWeekdayLabel: { width: '14.2857%', textAlign: 'center', fontSize: 12, fontWeight: '600', color: '#94a3b8' },
  calendarGrid: { flexDirection: 'column' },
  calendarWeekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  calendarDay: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: '#1e293b',
    paddingVertical: 8,
    marginHorizontal: 3,
    minHeight: 48,
  },
  calendarDayMuted: { opacity: 0.4, backgroundColor: '#0f172a' },
  calendarDaySelected: { borderColor: '#3b82f6', backgroundColor: '#1e40af', borderWidth: 2 },
  calendarDayToday: { borderColor: '#10b981', borderWidth: 2 },
  calendarDayLabel: { fontSize: 15, fontWeight: '600', color: '#f8fafc' },
  calendarDayLabelMuted: { color: '#64748b' },
  calendarDayLabelSelected: { color: '#ffffff' },
  calendarDayDot: { width: 6, height: 6, borderRadius: 3, marginTop: 4, backgroundColor: '#2563eb' },
  calendarSelectedActions: { marginTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  calendarSelectedLabel: { color: '#334155', fontWeight: '600' },
  calendarTodayButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, borderWidth: 1, borderColor: '#cbd5f5', backgroundColor: '#eef2ff' },
  calendarTodayLabel: { color: '#1d4ed8', fontWeight: '700' },
  calendarWrapper: { marginBottom: 24, padding: 20, backgroundColor: '#1e293b', borderRadius: 8, borderWidth: 1, borderColor: '#334155' },
  calendarInput: { backgroundColor: '#0f172a', padding: 12, borderRadius: 6, marginVertical: 10, borderWidth: 1, borderColor: '#334155', color: '#f8fafc', fontSize: 15 },
  calendarNoteEditor: { minHeight: 140, backgroundColor: '#0f172a', borderRadius: 6, padding: 16, marginBottom: 20, borderWidth: 1, borderColor: '#334155', color: '#f8fafc', fontSize: 15 },
  noteStageTitle: { fontWeight: '700', fontSize: 16, color: '#f8fafc', marginBottom: 8 },
  notePreviewLabel: { color: '#94a3b8', fontSize: 12, fontWeight: '600', marginTop: 4 },
  notePreviewText: { color: '#f8fafc', fontSize: 15, marginBottom: 12 },
  noteDateCard: { marginVertical: 12 },
  noteDateToggle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  noteDateToggleLabel: { color: '#94a3b8', fontWeight: '700' },
  noteDateCalendar: { marginTop: 12 },
  noteDateCalendarHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  noteDateCalendarTitle: { color: '#f8fafc', fontWeight: '700' },
  noteDateCalendarButton: { padding: 6, borderRadius: 999, borderWidth: 1, borderColor: '#334155' },
  noteDateCalendarButtonLabel: { color: '#f8fafc', fontWeight: '700' },
  noteDateWeekdays: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  noteDateWeekdayLabel: { width: '14.2857%', textAlign: 'center', color: '#94a3b8', fontSize: 12, fontWeight: '600' },
  noteDateGrid: { flexDirection: 'column' },
  noteDateDay: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#334155',
    marginHorizontal: 2,
  },
  noteDateDayMuted: { opacity: 0.4 },
  noteDateDayActive: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  noteDateDayLabel: { color: '#f8fafc', fontWeight: '600' },
  noteDateDayLabelMuted: { color: '#94a3b8' },
  noteDateDayLabelActive: { color: '#fff' },
  editModalOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
    zIndex: 40,
  },
  editModalPanel: {
    width: '100%',
    maxWidth: 600,
    backgroundColor: '#1e293b',
    borderRadius: 8,
    padding: 32,
    borderWidth: 1,
    borderColor: '#334155',
  },
  editModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  editModalTitle: { color: '#f8fafc', fontSize: 18, fontWeight: '700' },
  editModalClose: { color: '#94a3b8', fontSize: 22, fontWeight: '700', paddingHorizontal: 6 },
  editModalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 16 },
  stageActionsSingle: { alignItems: 'flex-end', marginTop: 16 },
  stageActions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 16, marginTop: 20 },
  stagePrimaryButton: { backgroundColor: '#1e40af', paddingVertical: 14, paddingHorizontal: 24, borderRadius: 6, alignItems: 'center', borderWidth: 1, borderColor: '#3b82f6' },
  stagePrimaryLabel: { color: '#fff', fontWeight: '700', fontSize: 15 },
  stageSecondaryButton: { paddingVertical: 14, paddingHorizontal: 24, borderRadius: 6, borderWidth: 1, borderColor: '#475569', backgroundColor: '#374151' },
  stageSecondaryLabel: { color: '#e2e8f0', fontWeight: '700', fontSize: 15 },
  calendarNotePane: { flex: 1, marginBottom: 24, padding: 20, backgroundColor: '#1e293b', borderRadius: 8, borderWidth: 1, borderColor: '#334155' },
  calendarNotePaneHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#334155' },
  calendarNotePaneTitle: { fontWeight: '800', fontSize: 18, color: '#f8fafc' },
  calendarNotePaneCount: { color: '#94a3b8', fontSize: 14 },
  calendarAddButton: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 6, borderWidth: 1, borderColor: '#3b82f6', backgroundColor: '#1e40af' },
  calendarAddButtonLabel: { color: '#ffffff', fontWeight: '700', fontSize: 14 },
  calendarNoteAlert: { marginBottom: 12 },
  calendarNoteLoading: { marginTop: 12 },
  calendarNoteEmpty: { color: '#9ca3af', marginTop: 12 },
  calendarSourceSummaryEmpty: { paddingVertical: 12, alignSelf: 'stretch' },
  calendarSourceSummary: { marginTop: 12, marginBottom: 16, padding: 12, borderRadius: 12, borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#111827', alignItems: 'center' },
  calendarSourceSummaryTitle: { alignSelf: 'flex-start', fontWeight: '700', color: '#e5e7eb', marginBottom: 8 },
  calendarSourceLegend: { marginTop: 12, alignSelf: 'stretch' },
  calendarSourceLegendRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 4 },
  calendarSourceLegendSwatch: { width: 14, height: 14, borderRadius: 7, marginRight: 8 },
  calendarSourceLegendLabel: { flex: 1, color: '#e5e7eb', fontWeight: '600' },
  calendarSourceLegendValue: { color: '#9ca3af', fontVariant: ['tabular-nums'] },
  calendarNoteList: { marginTop: 12 },
  calendarNoteCard: { backgroundColor: '#0f172a', padding: 16, borderRadius: 6, marginTop: 12, borderWidth: 1, borderColor: '#334155' },
  calendarNoteMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#1e293b' },
  calendarNoteBadge: { fontWeight: '700', color: '#3b82f6', fontSize: 14 },
  calendarNoteSource: { color: '#94a3b8', marginTop: 4, fontSize: 13 },
  noteActions: { flexDirection: 'row', gap: 16 },
  calendarNoteEdit: { color: '#06b6d4', fontWeight: '600', fontSize: 14 },
  calendarNoteDelete: { color: '#ef4444', fontWeight: '600', fontSize: 14 },
  calendarNoteText: { marginTop: 8, color: '#e2e8f0', fontSize: 15, lineHeight: 22 },
  calendarNoteDetail: { color: '#94a3b8', marginTop: 8, fontStyle: 'italic', fontSize: 13 },
  noteListDate: { color: '#94a3b8', fontSize: 12, marginBottom: 4 },
  pillGroup: { marginVertical: 12 },
  pillLabel: { fontWeight: '800', marginBottom: 10, color: '#f8fafc', fontSize: 16 },
  pillRow: { flexDirection: 'row', gap: 12, flexWrap: 'wrap' },
  pill: { paddingVertical: 10, paddingHorizontal: 16, backgroundColor: '#374151', borderRadius: 4, marginRight: 8, borderWidth: 1, borderColor: '#4b5563' },
  pillActive: { backgroundColor: '#1e40af', borderColor: '#3b82f6' },
  pillText: { color: '#d1d5db', fontSize: 14 },
  pillTextActive: { color: '#ffffff', fontWeight: '700' },
});
